apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
  labels:
    app: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/gcp-kubernetes-assignment/kubernetes-assignment/container1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: persistent-storage
              mountPath: /dhruv_PV_dir
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: k8s-volume
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer
