apiVersion: v1
kind: PersistentVolume
metadata:
  name: dhruv-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dhruv_PV_dir"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
